import test from "node:test";
import assert from "node:assert/strict";
import * as toteat from "../toteat.ts";

test("buildOrderCacheRows keeps Toteat order totals and deduplicates by order", () => {
  assert.equal(typeof toteat.buildOrderCacheRows, "function");
  if (typeof toteat.buildOrderCacheRows !== "function") return;

  const rows = toteat.buildOrderCacheRows([
    {
      orderId: 101,
      paymentId: 5001,
      paymentForms: [{ name: "Tarjeta Débito", id: 3000, amount: 45500, comment: "" }],
      fiscalId: "A-1",
      fiscalAmt: 45500,
      fiscalType: "BE",
      dateOpen: "2026-04-01T22:26:34",
      dateClosed: "2026-04-01T22:53:16",
      registerId: 1,
      registerName: "Caja 1",
      waiterId: 8,
      waiterName: "DAYNER CABARCAS",
      numberClients: 4,
      tableId: 11,
      tableName: "11",
      zoneId: "ZB.010",
      zoneName: "Salon Principal",
      subtotal: 42129.62,
      discounts: 1500,
      total: 45500,
      totalWithGratuity: 45500,
      taxes: 3370.38,
      gratuity: 0,
      payed: 45500,
      change: 0,
      products: [
        {
          id: "MON450",
          name: "Arma tu plato",
          netPrice: 26500,
          unitCost: 0,
          totalCost: 0,
          payed: 26500,
          quantity: 1,
          discounts: 0,
          taxes: 1962.96,
          hierarchyId: "AB.110",
          hierarchyName: "Arma tu plato",
        },
        {
          id: "ENT02",
          name: "LUMPIA X 1",
          netPrice: 5500,
          unitCost: 1569,
          totalCost: 1569,
          payed: 5500,
          quantity: 1,
          discounts: 0,
          taxes: 407.41,
          hierarchyId: "AB.010",
          hierarchyName: "Entradas",
        },
      ],
      client: {},
      comment: "",
      totalCost: 1569,
    },
    {
      orderId: 202,
      paymentId: 5002,
      paymentForms: [{ name: "Rappi", id: 9100, amount: 61200, comment: "" }],
      fiscalId: "A-2",
      fiscalAmt: 61200,
      fiscalType: "BE",
      dateOpen: "2026-04-02T12:10:00",
      dateClosed: "2026-04-02T12:30:00",
      registerId: 1,
      registerName: "Caja 1",
      waiterId: 9,
      waiterName: "OTRO",
      numberClients: 2,
      tableId: "V-10102",
      tableName: "Rappi Virtual",
      zoneId: "",
      zoneName: "",
      subtotal: 56666.67,
      discounts: 4200,
      total: 61200,
      totalWithGratuity: 61200,
      taxes: 4533.33,
      gratuity: 0,
      payed: 61200,
      change: 0,
      products: [
        {
          id: "COMP01",
          name: "COMBO 1- Valenciano personal",
          netPrice: 61200,
          unitCost: 9627,
          totalCost: 9627,
          payed: 61200,
          quantity: 1,
          discounts: 4200,
          taxes: 4533.33,
          hierarchyId: "AB.160",
          hierarchyName: "Combos personales",
        },
      ],
      client: {},
      comment: "pedido rappi",
      totalCost: 9627,
    },
    {
      orderId: 202,
      paymentId: 5003,
      paymentForms: [{ name: "Rappi", id: 9100, amount: 61200, comment: "split" }],
      fiscalId: "A-2",
      fiscalAmt: 61200,
      fiscalType: "BE",
      dateOpen: "2026-04-02T12:10:00",
      dateClosed: "2026-04-02T12:31:00",
      registerId: 1,
      registerName: "Caja 1",
      waiterId: 9,
      waiterName: "OTRO",
      numberClients: 2,
      tableId: "V-10102",
      tableName: "Rappi Virtual",
      zoneId: "",
      zoneName: "",
      subtotal: 56666.67,
      discounts: 4200,
      total: 61200,
      totalWithGratuity: 61200,
      taxes: 4533.33,
      gratuity: 0,
      payed: 61200,
      change: 0,
      products: [
        {
          id: "COMP01",
          name: "COMBO 1- Valenciano personal",
          netPrice: 61200,
          unitCost: 9627,
          totalCost: 9627,
          payed: 61200,
          quantity: 1,
          discounts: 4200,
          taxes: 4533.33,
          hierarchyId: "AB.160",
          hierarchyName: "Combos personales",
        },
      ],
      client: {},
      comment: "pedido rappi split",
      totalCost: 9627,
    },
  ]);

  assert.deepStrictEqual(rows, [
    {
      order_id: "101",
      date: "2026-04-01",
      channel: "Punto de Venta",
      total_sales: 45500,
      total_tax: 3370.38,
      total_discount: 1500,
      total_cost: 1569,
      counts_as_order: 1,
    },
    {
      order_id: "202",
      date: "2026-04-02",
      channel: "Rappi",
      total_sales: 61200,
      total_tax: 4533.33,
      total_discount: 4200,
      total_cost: 9627,
      counts_as_order: 1,
    },
  ]);
});

test("buildOrderCacheRows nets a fully credited BM/NC order and excludes it from the order count", () => {
  assert.equal(typeof toteat.buildOrderCacheRows, "function");
  if (typeof toteat.buildOrderCacheRows !== "function") return;

  const rows = toteat.buildOrderCacheRows([
    {
      orderId: 303,
      paymentId: 8001,
      paymentForms: [{ name: "Efectivo", id: 1000, amount: 41800, comment: "" }],
      fiscalId: "",
      fiscalAmt: 0,
      fiscalType: "BM",
      dateOpen: "2026-04-03T19:13:21",
      dateClosed: "2026-04-03T19:54:33",
      registerId: 1,
      registerName: "Caja 1",
      waiterId: 8,
      waiterName: "DAYNER CABARCAS",
      numberClients: 4,
      tableId: 2,
      tableName: "2",
      zoneId: "ZB.010",
      zoneName: "Salon Principal",
      subtotal: 41800,
      discounts: 0,
      total: 41800,
      totalWithGratuity: 41800,
      taxes: 0,
      gratuity: 0,
      payed: 50000,
      change: 8200,
      products: [],
      client: {},
      comment: "",
      totalCost: 0,
    },
    {
      orderId: 303,
      paymentId: 8002,
      paymentForms: [{ name: "Efectivo", id: 1000, amount: -41800, comment: "" }],
      fiscalId: "",
      fiscalAmt: 0,
      fiscalType: "NC",
      dateOpen: "2026-04-03T19:13:21",
      dateClosed: "2026-04-03T19:54:33",
      registerId: 1,
      registerName: "Caja 1",
      waiterId: 8,
      waiterName: "DAYNER CABARCAS",
      numberClients: 4,
      tableId: 2,
      tableName: "2",
      zoneId: "ZB.010",
      zoneName: "Salon Principal",
      subtotal: -41800,
      discounts: 0,
      total: -41800,
      totalWithGratuity: -41800,
      taxes: 0,
      gratuity: 0,
      payed: -50000,
      change: 0,
      products: [],
      client: {},
      comment: "",
      totalCost: 0,
    },
  ]);

  assert.deepStrictEqual(rows, [
    {
      order_id: "303",
      date: "2026-04-03",
      channel: "Punto de Venta",
      total_sales: 0,
      total_tax: 0,
      total_discount: 0,
      total_cost: 0,
      counts_as_order: 0,
    },
  ]);
});
